remote_theme: jekyll/minima@v2.5.1   # or omit @â€¦ to track latest, but pinning is safer
plugins:
  - jekyll-remote-theme

title: "Donna Graham FP&A"


header_pages:
  - about.md

minima:
  social_links:
    - platform: "LinkedIn"
      icon: square-linkedin
      url: [Donna Graham] (https://www.linkedin.com/in/donna-graham-685521179)
